// ┌─────────────────────────────────────────────────────────────────┐
// │  Storage 추상화 레이어                                            │
// │  Claude Artifacts Shared Storage로 전환 시 이 블록만 교체하면 됩니다  │
// └─────────────────────────────────────────────────────────────────┘
const Storage = {
  async get(key) {
    // TODO: Claude Artifacts Shared Storage API로 교체
    // 예시: return await window.claude.shared.get(key)
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
  },
  async set(key, value) {
    // TODO: Claude Artifacts Shared Storage API로 교체
    // 예시: await window.claude.shared.set(key, JSON.stringify(value))
    try { localStorage.setItem(key, JSON.stringify(value)); } catch(e) { throw e; }
  }
};

// ── SVG 아이콘 헬퍼 ──────────────────────────────────
const SVG={
  plus:`<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>`,
  x:`<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`,
  check:`<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`,
  edit:`<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>`,
  trash:`<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M9 6V4h6v2"/></svg>`,
  chevronRight:`<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>`,
  users:`<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>`,
  inbox:`<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></svg>`,
  history:`<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 .49-4.5"/></svg>`,
  listDetails:`<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>`,
  calendarEvent:`<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/><circle cx="12" cy="15" r="1" fill="currentColor"/></svg>`,
  list:`<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>`,
};

// ── 상수 ──────────────────────────────────────────────
const TRACK_META={common:{name:"공통",cls:"t-common",color:"#C2610A"},core:{name:"브랜드 코어 & 보이스",cls:"t-core",color:"#1D4ED8"},identity:{name:"브랜드 아이덴티티",cls:"t-id",color:"#15803D"},asset:{name:"브랜드 에셋",cls:"t-asset",color:"#4B5563"},site:{name:"브랜드 에셋 사이트",cls:"t-site",color:"#6D28D9"},film:{name:"브랜드 Film",cls:"t-film",color:"#BE123C"},collab:{name:"공동브랜딩",cls:"t-collab",color:"#7E22CE"}};
const SEP_MAP={W0:"5월 · 킥오프",W1:"6월 · Strategy",W5:"7월 · Development",W9:"8월 · Implementation",W13:"9월 · Review"};
const MAX_HISTORY=500;
function xlDate(s){const d=new Date(Math.round((s-25569)*86400*1000));return`${d.getUTCMonth()+1}/${d.getUTCDate()}`;}
const WEEK_DATES_INIT={W0:`${xlDate(46169)}–${xlDate(46171)}`,W1:`${xlDate(46174)}–${xlDate(46179)}`,W2:`${xlDate(46181)}–${xlDate(46185)}`,W3:`${xlDate(46188)}–${xlDate(46192)}`,W4:`${xlDate(46194)}–${xlDate(46199)}`,W5:`${xlDate(46202)}–${xlDate(46206)}`,W6:`${xlDate(46209)}–${xlDate(46213)}`,W7:`${xlDate(46216)}–${xlDate(46220)}`,W8:`${xlDate(46223)}–${xlDate(46227)}`,W9:`${xlDate(46230)}–${xlDate(46234)}`,W10:`${xlDate(46237)}–${xlDate(46241)}`,W11:`${xlDate(46244)}–${xlDate(46248)}`,W12:`${xlDate(46251)}–${xlDate(46255)}`,W13:`${xlDate(46258)}–${xlDate(46262)}`,W14:`${xlDate(46265)}–${xlDate(46269)}`,W15:`${xlDate(46272)}–${xlDate(46276)}`,W16:`${xlDate(46279)}–${xlDate(46283)}`};
const WEEK_ORDER_INIT=["W0","W1","W2","W3","W4","W5","W6","W7","W8","W9","W10","W11","W12","W13","W14","W15","W16"];
const AV_COLORS=["#DBEAFE,#1E40AF","#DCFCE7,#166534","#FCE7F3,#9D174D","#FEF3C7,#92400E","#EDE9FE,#5B21B6","#FFF7ED,#9A3412","#F0FDF4,#15803D","#FEF2F2,#991B1B"];
const INIT_DATA=[
  {w:"W0",m:"킥오프 주간",b:"킥오프",t:"common",task:"킥오프 미팅"},{w:"W0",t:"common",task:"각 카테고리별 업무 항목 정의"},{w:"W0",t:"common",task:"상세 업무 계획 수립"},
  {w:"W1",m:"리서치 & 코어 착수",b:"진행",t:"core",task:"글로벌 레퍼런스 리서치 및 인사이트 정리"},{w:"W1",t:"core",task:"브랜드 현황 파악 - 1차 결과물 검토 및 업데이트 범위 확인"},{w:"W1",t:"core",task:"내부 인터뷰 설계 - 질문 구조 및 대상자 선정 (검토)"},{w:"W1",t:"identity",task:"로고 마스터 시스템 정의 : 확정 로고 그리드 시스템 별 적용 / 메인로고 조형 수정"},{w:"W1",t:"identity",task:"브랜드 아키텍처 전체 로고(서브브랜드) 대입 : 일관성 검토 / 디자인 수정 및 타이포 확정"},{w:"W1",t:"collab",task:"인터뷰지 분석 및 우선순위 정리"},{w:"W1",t:"collab",task:"네이밍 아이데이션"},
  {w:"W2",m:"코어 초안",b:"진행",t:"core",task:"내부 인터뷰 실시 - 브랜드 인식 분석 (검토)"},{w:"W2",t:"core",task:"브랜드 MVC 초안 작성"},{w:"W2",t:"core",task:"글로벌 보이스 원칙 초안 - 'Beyond the Standard' 체계화"},{w:"W2",t:"identity",task:"브랜드 아키텍처 전체 로고(서브브랜드): 세로형 고려 / 가로형·세로형 방향 제작"},{w:"W2",t:"identity",task:"브랜드 컬러 체계 초안 착수(1차) / 메인 + 서브 브랜드 컬러"},{w:"W2",t:"identity",task:"기존 키비주얼 현황 체크 및 에셋 레퍼런스 조사 / 3D 굿즈·공간 중심"},{w:"W2",t:"film",task:"로고 모션그래픽 현황 및 비주얼 레퍼런스 조사 / 로고·벡터 모션 중심"},
  {w:"W3",m:"브랜드 전략 및 내러티브",b:"진행",t:"core",task:"브랜드 내러티브 시스템 구조화 (기업BI, 서비스BI)"},{w:"W3",t:"core",task:"시장별 메시지 코어 초안 (대표 시장 선정)"},{w:"W3",t:"core",task:"태그라인 후보군 1차 도출 및 내부 검토"},{w:"W3",t:"identity",task:"브랜드 컬러 체계 초안 착수(2차) / 메인 + 서브 브랜드 컬러"},{w:"W3",t:"identity",task:"로고 마스터 시스템 1차 내부 보고: 방향성 확정 / 로고+서브브랜드로고+컬러 보고장표 제작"},{w:"W3",t:"film",task:"로고 모션그래픽 비주얼 제안 / 로고·벡터 모션 중심"},
  {w:"W4",m:"전략 확정 및 1차 중간보고",b:"마일스톤",t:"core",task:"브랜드 원칙, MVC 내부 보고 및 확정"},{w:"W4",t:"core",task:"톤앤매너 가이드라인 초안 작성"},{w:"W4",t:"core",task:"채널별 커뮤니케이션 기준 정리"},{w:"W4",t:"identity",task:"브랜드 로고 + 컬러 체계 확정 / 로고 시스템 전반 보완, 레터링 셋, 가이드 작성 착수"},{w:"W4",t:"identity",task:"타이포그래피 시스템 구축 - KR/EN 서체 선정 및 스케일 정의 / 브랜드 폰트"},{w:"W4",t:"identity",task:"기존 키비주얼 보완 및 에셋 리소스 제작 / 3D 씬 제작"},{w:"W4",t:"film",task:"로고 모션그래픽 제작"},
  {w:"W5",m:"비주얼 시스템 구축 착수",b:"진행",t:"core",task:"태그라인 확정 및 글로벌 버전 병행 작업"},{w:"W5",t:"core",task:"브랜드 보이스 예시 콘텐츠 초안 (In-use, Misuse)"},{w:"W5",t:"identity",task:"브랜드 그래픽 모티브 라이브러리 방향 설정 / 레퍼런스·작업방향 싱크"},{w:"W5",t:"identity",task:"브랜드 키비주얼 시안 제작 / (2D) 패턴 배리에이션 / (3D) 굿즈·오프라인 배리에이션"},{w:"W5",t:"asset",task:"브랜드 모션&영상 아이덴티티(1/4차): 기획안 작성 / 로고모션·아이덴티티 제작 싱크"},{w:"W5",t:"asset",task:"브랜드 모션&영상 아이덴티티(2/4차): 컨셉방향"},
  {w:"W6",m:"키비주얼, 아이콘, 모션 설계",b:"진행",t:"identity",task:"아이콘 시스템(1/2차) : 구조 설계(스타일 가이드) / 니즈 파악 및 목업제작"},{w:"W6",t:"asset",task:"브랜드 모션&영상 아이덴티티(2/4차): 제작 / 제작 디밸롭"},{w:"W6",t:"asset",task:"브랜드 모션&영상 아이덴티티(2/4차): 가이드 작성 / 트랜지션 원칙, 속도감"},{w:"W6",t:"film",task:"브랜드 Film 기획 작업"},{w:"W6",t:"film",task:"브랜드 Film 기획 작업 / 비주얼 레퍼런스 수집·컨셉방향"},
  {w:"W7",m:"프로토타입",b:"진행",t:"identity",task:"디자인 토큰 정의: 컬러, 타이포, 스페이스, 모션 / 개발 연동을 위한 수치화"},{w:"W7",t:"identity",task:"모듈러 방식 비주얼 에셋 구조화 / 리소스, 영상 비주얼가이드, 템플릿 가이드 정리·제작"},{w:"W7",t:"film",task:"브랜드 Film 키스크린 작업 / 이미지 컨셉 작업"},
  {w:"W8",m:"가이드라인 고도화",b:"마일스톤",t:"identity",task:"프로토타입 (업비트 서비스 목업) 적용 테스트 및 보완"},{w:"W8",t:"identity",task:"아이콘 시스템(2/2차): 키비주얼 / 목업 테스트"},{w:"W8",t:"film",task:"브랜드 Film 키스크린 작업 2차"},{w:"W8",t:"film",task:"브랜드 Film 3D 에셋 상세 착수"},
  {w:"W9",m:"브랜드 에셋 사이트 설계",b:"진행",t:"identity",task:"온 오프라인 적용 목업"},{w:"W9",t:"asset",task:"AI 기반 브랜드 에셋 설계(1/3차): 재조합 컴포넌트 워크플로우 설계 / 아이콘·비주얼 에셋"},{w:"W9",t:"asset",task:"커뮤니케이션 비주얼 템플릿(1/1차): 제작 착수 (Slide, SNS용)"},{w:"W9",t:"site",task:"에셋 사이트 IA 설계"},{w:"W9",t:"site",task:"콘텐츠 분류 체계 확정"},{w:"W9",t:"film",task:"브랜드 Film 키스크린 최종 확정"},{w:"W9",t:"film",task:"브랜드 Film 3D 에셋 제작 방향성 검토"},{w:"W9",t:"film",task:"브랜드 Film 편집 진행"},
  {w:"W10",m:"사이트 와이어프레임 작업",b:"진행",t:"asset",task:"AI 기반 브랜드 에셋(2/3차): 에셋 자동화 워크플로우 테스트"},{w:"W10",t:"asset",task:"AI 기반 브랜드 에셋(2/3차): 거버넌스 룰 초안 작성"},{w:"W10",t:"site",task:"사이트 인터랙션 정의"},{w:"W10",t:"site",task:"콘텐츠 내용 와이어프레임 적용"},
  {w:"W11",m:"사이트 구축 및 에셋 통합",b:"진행",t:"identity",task:"Figma 가이드 정비 진행"},{w:"W11",t:"asset",task:"커뮤니케이션 비주얼 템플릿(2/2차): 완성 및 목업 검증"},{w:"W11",t:"asset",task:"브랜드 에셋 및 에셋 사이트 중간 보고"},{w:"W11",t:"asset",task:"AI 기반 브랜드 에셋(3/3차): 생성 가이드 작성"},{w:"W11",t:"site",task:"에셋 사이트 내부 리뷰"},{w:"W11",t:"site",task:"에셋 사이트 주요 섹션 개발"},{w:"W11",t:"film",task:"브랜드 Film 편집 1차본 검토"},
  {w:"W12",m:"사이트 QA",b:"마일스톤",t:"site",task:"에셋 사이트 전체 검증"},{w:"W12",t:"film",task:"브랜드 Film 편집 2차 (수정안) 검토"},
  {w:"W13",m:"최종 리뷰 준비",b:"마무리",t:"identity",task:"최종 보고 문서 작성 및 방향성 싱크 / 문서용 비주얼 재정의·추가제작"},{w:"W13",t:"film",task:"브랜드 Film 편집 최종 검토"},
  {w:"W14",m:"문서 덱작업",b:"마무리",t:"identity",task:"최종 보고 덱작업 / 슬라이드용 비주얼 업데이트·제작"},
  {w:"W15",m:"최종보고",b:"최종",t:"identity",task:"C레벨 최종 보고 / 덱 비주얼 디밸롭"},
  {w:"W16",m:"산출물 정리",b:"마무리",t:"identity",task:"산출물 배포 준비 / 에셋, 가이드, 템플릿 등"}
];

let WEEK_DATES={...WEEK_DATES_INIT},WEEK_ORDER=[...WEEK_ORDER_INIT];
let BADGES=[{name:"킥오프",bg:"#FAEEDA",ft:"#633806"},{name:"진행",bg:"#ECFDF5",ft:"#065F46"},{name:"마일스톤",bg:"#FEF3C7",ft:"#92400E"},{name:"마무리",bg:"#F3F4F6",ft:"#374151"},{name:"최종",bg:"#FEE2E2",ft:"#991B1B"}];

const SK={data:"dunamu-tracker-v1",members:"dunamu-tracker-members-v1"};
let members=[],currentUser=null,nextMId=1,nextId=0,tasks=[],checks={},assignees={};
let currentFilter="all",pendingDeleteId=null,history_log=[],sectionOpen={track:true,week:true},currentDetailMid=null,saveTimer=null;

function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function avColors(i){const p=AV_COLORS[i%AV_COLORS.length].split(",");return{bg:p[0],ft:p[1]};}
function initials(n){return n.slice(0,2);}
function nowStr(){return new Date().toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"});}
function getCurrentWeek(){const today=new Date();let ff=null;for(let i=0;i<WEEK_ORDER.length;i++){const w=WEEK_ORDER[i],d=WEEK_DATES[w];if(!d)continue;const pts=d.split("–");if(pts.length<2)continue;const[sm,sd]=pts[0].trim().split("/").map(Number);const[em,ed]=pts[1].trim().split("/").map(Number);const yr=today.getFullYear();const s=new Date(yr,sm-1,sd),e=new Date(yr,em-1,ed,23,59,59);if(today>=s&&today<=e)return w;if(today<s&&!ff)ff=w;}return ff||WEEK_ORDER[WEEK_ORDER.length-1];}
function toggleSection(k){sectionOpen[k]=!sectionOpen[k];document.getElementById("toggle-body-"+k).classList.toggle("open",sectionOpen[k]);document.getElementById("toggle-icon-"+k).classList.toggle("open",sectionOpen[k]);}
function positionEl(el,trig,w){el.style.display="block";const r=trig.getBoundingClientRect(),eh=el.offsetHeight||160,vw=window.innerWidth,vh=window.innerHeight;let left=r.left,top=r.bottom+8;if(left+w>vw-8)left=vw-w-8;if(left<8)left=8;if(top+eh>vh-8)top=r.top-eh-8;el.style.left=left+"px";el.style.top=top+"px";}

// ── 저장/로드 (window.storage shared API) ────────────
function showSaving(){const el=document.getElementById("save-indicator");el.className="save-indicator saving";document.getElementById("save-text").textContent="저장 중...";}
function showSaved(){const el=document.getElementById("save-indicator");el.className="save-indicator saved";document.getElementById("save-text").textContent="저장됨";setTimeout(()=>el.className="save-indicator hidden",2000);}
function scheduleSave(){
  showSaving();
  if(saveTimer)clearTimeout(saveTimer);
  saveTimer=setTimeout(async()=>{
    try{
      await window.storage.set(SK.data, JSON.stringify({tasks,checks,assignees,history_log,WEEK_DATES,WEEK_ORDER,BADGES,nextId}), true);
      await window.storage.set(SK.members, JSON.stringify({members,nextMId}), true);
      showSaved();
    }catch(e){document.getElementById("save-indicator").className="save-indicator hidden";}
  },500);
}

async function loadAll(){
  try{
    const mRes=await window.storage.get(SK.members, true);
    if(mRes){const mData=JSON.parse(mRes.value);members=mData.members||[];nextMId=mData.nextMId||1;}
    const dRes=await window.storage.get(SK.data, true);
    if(dRes){
      const dData=JSON.parse(dRes.value);
      tasks=dData.tasks||[];
      const fc={};Object.entries(dData.checks||{}).forEach(([k,v])=>{fc[parseInt(k)]=v;});checks=fc;
      const fa={};Object.entries(dData.assignees||{}).forEach(([k,v])=>{fa[parseInt(k)]=v;});assignees=fa;
      history_log=dData.history_log||[];
      WEEK_DATES=dData.WEEK_DATES||{...WEEK_DATES_INIT};
      WEEK_ORDER=dData.WEEK_ORDER||[...WEEK_ORDER_INIT];
      BADGES=dData.BADGES||BADGES;
      nextId=dData.nextId||0;
      return true;
    }
  }catch(e){}
  return false;
}

async function startApp(){
  const has=await loadAll();
  if(!has){tasks=INIT_DATA.map(r=>{const id=nextId++;checks[id]=false;assignees[id]=[];return{id,w:r.w,d:WEEK_DATES[r.w]||"",m:r.m||"",b:r.b||"",t:r.t,task:r.task};});}
  document.getElementById("loading-overlay").style.display="none";
  document.getElementById("login-screen").style.display="flex";
  renderLoginList();
}
startApp();

function addHistory(t,d,dt=""){history_log.unshift({type:t,who:currentUser?.name||"?",when:nowStr(),desc:d,detail:dt});if(history_log.length>MAX_HISTORY)history_log.length=MAX_HISTORY;scheduleSave();}

function renderLoginList(){const el=document.getElementById("login-member-list");el.innerHTML=members.length?"":`<p style="font-size:13px;color:var(--text2);text-align:center;padding:8px 0">아직 등록된 팀원이 없어요</p>`;members.forEach(m=>{const c=avColors(m.colorIdx);const btn=document.createElement("button");btn.className="member-btn";btn.innerHTML=`<div class="avatar" style="width:32px;height:32px;font-size:12px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><div class="member-info"><div class="member-name-lg">${esc(m.name)}</div><div class="member-role-sm">${esc(m.role)}</div></div>${SVG.chevronRight}`;btn.onclick=()=>login(m);el.appendChild(btn);});}
function registerAndLogin(){const name=document.getElementById("login-new-name").value.trim(),role=document.getElementById("login-new-role").value.trim();if(!name){alert("이름을 입력하세요.");return;}if(members.find(m=>m.name===name)){alert("이미 등록된 이름입니다.");return;}const m={id:nextMId++,name,role:role||"팀원",colorIdx:members.length};members.push(m);scheduleSave();login(m);}
function login(m){currentUser=m;document.getElementById("login-screen").style.display="none";document.getElementById("app").style.display="block";const c=avColors(m.colorIdx);const av=document.getElementById("cur-av");av.textContent=initials(m.name);av.style.background=c.bg;av.style.color=c.ft;document.getElementById("cur-name").textContent=m.name;renderAll();renderMemberGrid();}
function logout(){currentUser=null;currentDetailMid=null;document.getElementById("app").style.display="none";document.getElementById("login-screen").style.display="flex";document.getElementById("login-new-name").value="";document.getElementById("login-new-role").value="";renderLoginList();}
function showPage(id,btn){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav-tab").forEach(b=>b.classList.remove("active"));document.getElementById("page-"+id).classList.add("active");if(btn)btn.classList.add("active");if(id==="history")renderHistory();if(id==="workload")renderWorkload();if(id==="members")renderMemberGrid();}
function toggle(id){checks[id]=!checks[id];const row=document.getElementById("row-"+id);if(row){row.classList.toggle("done-row",checks[id]);const cb=row.querySelector("input[type=checkbox]");if(cb)cb.checked=checks[id];}calcStats();renderWeekMini();renderTrackBars();if(currentDetailMid!==null){refreshDetailStats(currentDetailMid);refreshDetailItem(id);}scheduleSave();}
function refreshDetailStats(mid){const all=tasks.filter(t=>assignees[t.id]?.includes(mid));const done=all.filter(t=>checks[t.id]).length,total=all.length,pct=total?Math.round(done/total*100):0;const nums=document.querySelectorAll("#detail-header .detail-stat-num");if(nums.length>=4){nums[0].textContent=total;nums[1].textContent=done;nums[2].textContent=total-done;nums[3].textContent=pct+"%";}}
function refreshDetailItem(taskId){const item=document.getElementById("ditem-"+taskId);if(!item)return;const isDone=checks[taskId];item.classList.toggle("done",isDone);const cb=item.querySelector("input[type=checkbox]");if(cb)cb.checked=isDone;}
function renderWorkload(){const el=document.getElementById("workload-grid");el.innerHTML="";if(!members.length){el.innerHTML=`<div class="empty-state">${SVG.users}팀원을 먼저 등록하세요</div>`;return;}const cw=getCurrentWeek();members.forEach(m=>{const c=avColors(m.colorIdx),all=tasks.filter(t=>assignees[t.id]?.includes(m.id)),tw=all.filter(t=>t.w===cw);const done=all.filter(t=>checks[t.id]).length,total=all.length,pct=total?Math.round(done/total*100):0;const div=document.createElement("div");div.className="wl-card";const tHtml=tw.slice(0,3).map(t=>{const tm=TRACK_META[t.t];const label=t.task.length>22?t.task.slice(0,22)+"…":t.task;return`<div class="wl-task-row"><span style="width:7px;height:7px;border-radius:50%;background:${tm?.color||"#888"};display:inline-block;flex-shrink:0"></span><span style="${checks[t.id]?"text-decoration:line-through;opacity:.4":""}">${esc(label)}</span></div>`;}).join("");div.innerHTML=`<div class="wl-header"><div class="avatar" style="width:36px;height:36px;font-size:13px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><div style="flex:1;min-width:0"><div class="wl-name">${esc(m.name)}</div><div class="wl-count">${done}/${total} 완료 · ${pct}%</div></div></div><div class="wl-bar-wrap"><div class="wl-bar-fill" style="width:${pct}%;background:${c.ft}"></div></div>${tw.length?`<div style="font-size:11px;font-weight:600;color:var(--text3);letter-spacing:.04em;text-transform:uppercase;margin-bottom:6px">${cw} 이번 주 업무</div>`:""}<div class="wl-tasks">${tHtml||`<div style="font-size:13px;color:var(--text2)">이번 주 배정 항목 없음</div>`}</div>${total>0?`<div class="wl-more" onclick="showMemberDetail(${m.id})">${SVG.listDetails} 전체 ${total}개 보기</div>`:""}`;el.appendChild(div);});}
function showMemberDetail(mid){currentDetailMid=mid;const m=members.find(x=>x.id===mid);if(!m)return;const c=avColors(m.colorIdx),all=tasks.filter(t=>assignees[t.id]?.includes(mid));const done=all.filter(t=>checks[t.id]).length,total=all.length,pct=total?Math.round(done/total*100):0,cw=getCurrentWeek();document.getElementById("detail-header").innerHTML=`<div class="avatar" style="width:48px;height:48px;font-size:16px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><div><div style="font-size:18px;font-weight:600;letter-spacing:-.02em">${esc(m.name)}</div><div style="font-size:13px;color:var(--text2);margin-top:2px">${esc(m.role)}</div></div><div class="detail-stats"><div class="detail-stat"><div class="detail-stat-num">${total}</div><div class="detail-stat-lbl">전체</div></div><div class="detail-stat"><div class="detail-stat-num" style="color:#059669">${done}</div><div class="detail-stat-lbl">완료</div></div><div class="detail-stat"><div class="detail-stat-num" style="color:var(--b-md)">${total-done}</div><div class="detail-stat-lbl">진행중</div></div><div class="detail-stat"><div class="detail-stat-num">${pct}%</div><div class="detail-stat-lbl">완성율</div></div></div>`;const tw=all.filter(t=>t.w===cw),others=all.filter(t=>t.w!==cw);function tItem(t){const tm=TRACK_META[t.t];const isDone=checks[t.id];return`<div class="detail-task-item${isDone?" done":""}" id="ditem-${t.id}"><input type="checkbox" ${isDone?"checked":""} onchange="toggle(${t.id})" style="width:15px;height:15px;margin-top:3px;cursor:pointer;accent-color:var(--b-md);flex-shrink:0"><div style="flex:1;min-width:0"><div class="detail-task-text">${esc(t.task)}</div><div class="detail-task-meta"><span class="week-info-badge"><span>${esc(t.w)}</span><span style="opacity:.4;font-size:10px">|</span><span>${esc(t.d||"—")}</span></span><span class="tp ${tm?.cls||""}"><span style="width:6px;height:6px;border-radius:50%;background:${tm?.color||"#888"};display:inline-block;flex-shrink:0"></span>${tm?.name||esc(t.t)}</span></div></div></div>`;}let body="";if(tw.length){body+=`<div class="detail-section-title">${SVG.calendarEvent}${cw} 이번 주 업무<span style="background:#DCFCE7;color:#15803D;font-size:11px;padding:2px 8px;border-radius:999px;font-weight:600;text-transform:none;letter-spacing:0">${tw.filter(t=>checks[t.id]).length}/${tw.length}</span></div><div class="detail-task-list">${tw.map(tItem).join("")}</div>`;}if(others.length){body+=`<div class="detail-section-title">${SVG.list} 전체 업무 목록</div><div class="detail-task-list">${others.map(tItem).join("")}</div>`;}if(!total)body=`<div class="empty-state">${SVG.inbox}배정된 업무가 없습니다</div>`;document.getElementById("detail-body").innerHTML=body;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("page-workload-detail").classList.add("active");}
function showWorkloadList(){currentDetailMid=null;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("page-workload").classList.add("active");document.querySelectorAll(".nav-tab").forEach(b=>b.classList.toggle("active",b.textContent==="담당자 현황"));renderWorkload();}
function addMember(){const name=document.getElementById("new-m-name").value.trim(),role=document.getElementById("new-m-role").value.trim();if(!name){alert("이름을 입력하세요.");return;}if(members.find(m=>m.name===name)){alert("이미 등록된 이름입니다.");return;}members.push({id:nextMId++,name,role:role||"팀원",colorIdx:members.length,editing:false});document.getElementById("new-m-name").value="";document.getElementById("new-m-role").value="";renderMemberGrid();renderLoginList();scheduleSave();}
function toggleEditMember(id){members=members.map(m=>({...m,editing:m.id===id?!m.editing:false}));renderMemberGrid();}
function saveMemberEdit(id){const nn=document.getElementById("medit-name-"+id)?.value.trim(),nr=document.getElementById("medit-role-"+id)?.value.trim();if(!nn){alert("이름을 입력하세요.");return;}if(members.find(m=>m.name===nn&&m.id!==id)){alert("이미 존재하는 이름입니다.");return;}members=members.map(m=>m.id===id?{...m,name:nn,role:nr||m.role,editing:false}:m);if(currentUser?.id===id){currentUser={...currentUser,name:nn,role:nr||currentUser.role};const c=avColors(currentUser.colorIdx);const av=document.getElementById("cur-av");av.textContent=initials(currentUser.name);av.style.background=c.bg;av.style.color=c.ft;document.getElementById("cur-name").textContent=currentUser.name;}renderMemberGrid();renderLoginList();scheduleSave();}
function deleteMember(id,trig){const m=members.find(x=>x.id===id);if(!m)return;if(m.id===currentUser?.id){alert("현재 로그인 중인 계정은 삭제할 수 없어요.");return;}pendingDeleteId="member_"+id;document.getElementById("del-pop-msg").textContent=`'${m.name}'님을 팀원에서 삭제합니다.`;document.getElementById("del-overlay").style.display="block";setTimeout(()=>positionEl(document.getElementById("del-pop"),trig,280),0);}
function renderMemberGrid(){const el=document.getElementById("member-grid");el.innerHTML="";if(!members.length){el.innerHTML=`<p style="font-size:14px;color:var(--text2)">등록된 팀원이 없습니다.</p>`;return;}members.forEach(m=>{const c=avColors(m.colorIdx);const isCur=m.id===currentUser?.id;const div=document.createElement("div");div.className="member-card";if(m.editing){div.innerHTML=`<div class="mc-top"><div class="avatar" style="width:36px;height:36px;font-size:13px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><div class="mc-info"><div class="mc-name">${esc(m.name)}</div><div class="mc-role">${esc(m.role)}</div></div></div><div class="mc-edit-row"><input class="form-input" id="medit-name-${m.id}" value="${esc(m.name)}" placeholder="이름"><input class="form-input" id="medit-role-${m.id}" value="${esc(m.role)}" placeholder="역할"></div><div class="mc-actions"><button class="btn btn-sm btn-ghost" onclick="toggleEditMember(${m.id})">취소</button><button class="btn btn-primary btn-sm" onclick="saveMemberEdit(${m.id})">${SVG.check} 저장</button></div>`;}else{div.innerHTML=`<div class="mc-top"><div class="avatar" style="width:36px;height:36px;font-size:13px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><div class="mc-info"><div class="mc-name">${esc(m.name)}${isCur?' <span style="font-size:11px;color:var(--b-md)">(나)</span>':""}</div><div class="mc-role">${esc(m.role)}</div></div></div><div class="mc-actions"><button class="btn btn-sm btn-ghost" onclick="toggleEditMember(${m.id})">${SVG.edit} 수정</button>${!isCur?`<button class="btn btn-sm btn-ghost btn-danger" onclick="deleteMember(${m.id},this)">${SVG.trash} 삭제</button>`:""}</div>`;}el.appendChild(div);});}
function renderHistory(){const el=document.getElementById("history-list");if(!history_log.length){el.innerHTML=`<div class="empty-state">${SVG.history}아직 변경 내역이 없습니다</div>`;return;}el.innerHTML=`<div class="history-list-wrap">${history_log.map(h=>`<div class="history-item h-${h.type}"><div class="history-meta"><span class="history-badge">${h.type==="add"?"추가":h.type==="edit"?"수정":"삭제"}</span><span class="history-who">${esc(h.who)}</span><span class="history-when">${esc(h.when)}</span></div><div class="history-content">${esc(h.desc)}</div>${h.detail?`<div class="history-detail">${esc(h.detail)}</div>`:""}</div>`).join("")}</div>`;}
function clearHistory(){history_log=[];renderHistory();scheduleSave();}
function populateWeekSelect(sel){const el=document.getElementById("f-week");el.innerHTML="";WEEK_ORDER.forEach(w=>{const o=document.createElement("option");o.value=w;o.textContent=w+(WEEK_DATES[w]?" ("+WEEK_DATES[w]+")":"");if(w===sel)o.selected=true;el.appendChild(o);});const nw=document.createElement("option");nw.value="__new__";nw.textContent="+ 새 주차 추가...";el.appendChild(nw);}
function onWeekChange(){const val=document.getElementById("f-week").value;if(val==="__new__"){document.getElementById("new-week-row").style.display="block";document.getElementById("f-dates").value="";document.getElementById("f-main").value="";document.getElementById("f-main").disabled=false;document.getElementById("main-hint").textContent="(새 주차)";}else{document.getElementById("new-week-row").style.display="none";document.getElementById("f-dates").value=WEEK_DATES[val]||"";updateMainField(val);}}
function updateMainField(w,eid){const inp=document.getElementById("f-main"),hint=document.getElementById("main-hint");const ex=tasks.find(t=>t.w===w&&t.m&&(eid===undefined||t.id!==eid));if(ex){inp.value=ex.m;inp.disabled=true;hint.textContent="(기존 주차)";}else{inp.value="";inp.disabled=false;hint.textContent="(새 주차)";}}
function renderAssigneeChecks(sids){const el=document.getElementById("assignee-checks");el.innerHTML="";if(!members.length){el.innerHTML=`<div style="font-size:13px;color:var(--text2)">팀원을 먼저 등록하세요</div>`;return;}members.forEach(m=>{const c=avColors(m.colorIdx);const sel=sids.includes(m.id);const row=document.createElement("div");row.className="ac-row"+(sel?" selected":"");row.dataset.mid=m.id;row.innerHTML=`<div class="avatar" style="width:24px;height:24px;font-size:10px;background:${c.bg};color:${c.ft}">${esc(initials(m.name))}</div><span style="font-size:13px;flex:1;font-weight:500">${esc(m.name)}</span><span style="font-size:12px;color:var(--text2)">${esc(m.role)}</span>${sel?`<span class="chk-ic" style="color:var(--b-md);display:flex">${SVG.check}</span>`:""}`;row.onclick=()=>{row.classList.toggle("selected");const ic=row.querySelector(".chk-ic");if(row.classList.contains("selected")){if(!ic){const s=document.createElement("span");s.className="chk-ic";s.style.cssText="color:var(--b-md);display:flex";s.innerHTML=SVG.check;row.appendChild(s);}}else{if(ic)ic.remove();}};el.appendChild(row);});}
function getSelectedAssignees(){return[...document.querySelectorAll(".ac-row.selected")].map(r=>parseInt(r.dataset.mid));}
function positionPopover(trig){const pop=document.getElementById("popover");pop.style.display="block";const r=trig.getBoundingClientRect(),pw=320,ph=pop.offsetHeight||520,vw=window.innerWidth,vh=window.innerHeight;let left=r.right+10,top=r.top;if(left+pw>vw-8)left=r.left-pw-10;if(left<8)left=8;if(top+ph>vh-8)top=Math.max(8,vh-ph-8);pop.style.left=left+"px";pop.style.top=top+"px";}
function openAddPopover(){document.getElementById("pop-title").textContent="항목 추가";document.getElementById("edit-id").value="";document.getElementById("btn-delete").style.display="none";document.getElementById("new-week-row").style.display="none";const dw=currentFilter!=="all"?currentFilter:"W1";populateWeekSelect(dw);document.getElementById("f-dates").value=WEEK_DATES[dw]||"";document.getElementById("f-new-name").value="";document.getElementById("f-new-dates").value="";document.getElementById("f-track").value="core";document.getElementById("f-task").value="";updateMainField(dw);renderAssigneeChecks([]);document.getElementById("overlay").style.display="block";positionPopover(document.getElementById("btn-add-main"));}
function openEditPopover(id,trig){const task=tasks.find(t=>t.id===id);if(!task)return;document.getElementById("pop-title").textContent="항목 수정";document.getElementById("edit-id").value=id;document.getElementById("btn-delete").style.display="inline-flex";document.getElementById("new-week-row").style.display="none";populateWeekSelect(task.w);document.getElementById("f-dates").value=task.d;document.getElementById("f-new-name").value="";document.getElementById("f-new-dates").value="";document.getElementById("f-track").value=task.t;document.getElementById("f-task").value=task.task;updateMainField(task.w,task.id);renderAssigneeChecks(assignees[id]||[]);document.getElementById("overlay").style.display="block";positionPopover(trig);}
function closePopover(){document.getElementById("popover").style.display="none";document.getElementById("overlay").style.display="none";}
function saveTask(){let w=document.getElementById("f-week").value,d="";if(w==="__new__"){const nn=document.getElementById("f-new-name").value.trim(),nd=document.getElementById("f-new-dates").value.trim();if(!nn){alert("새 주차 이름을 입력하세요.");return;}if(!nd){alert("새 주차 기간을 입력하세요.");return;}if(WEEK_ORDER.includes(nn)){alert("이미 존재하는 주차 이름입니다.");return;}w=nn;d=nd;WEEK_DATES[w]=d;WEEK_ORDER.push(w);}else{d=WEEK_DATES[w]||"";}const mInp=document.getElementById("f-main"),m=mInp.disabled?(tasks.find(t=>t.w===w&&t.m)||{m:""}).m:mInp.value.trim();const t=document.getElementById("f-track").value,task=document.getElementById("f-task").value.trim();if(!task){alert("업무 내용은 필수입니다.");return;}const sel=getSelectedAssignees(),editId=document.getElementById("edit-id").value;if(editId===""){const nt={id:nextId++,w,d,m,b:"",t,task};tasks.push(nt);checks[nt.id]=false;assignees[nt.id]=sel;addHistory("add",`"${task}" 추가`);}else{const idx=tasks.findIndex(tk=>tk.id===parseInt(editId));if(idx>-1){tasks[idx]={...tasks[idx],w,d,m,t,task};assignees[parseInt(editId)]=sel;}addHistory("edit",`"${task}" 수정`);}closePopover();renderAll();}
function confirmDelete(evt){const editId=document.getElementById("edit-id").value;if(!editId)return;pendingDeleteId=parseInt(editId);const task=tasks.find(t=>t.id===pendingDeleteId);document.getElementById("del-pop-msg").textContent=`"${task?.task||""}" 항목을 삭제합니다.`;document.getElementById("del-overlay").style.display="block";setTimeout(()=>positionEl(document.getElementById("del-pop"),document.getElementById("btn-delete"),280),0);}
function closeDelPop(){document.getElementById("del-pop").style.display="none";document.getElementById("del-overlay").style.display="none";if(typeof pendingDeleteId==="string"&&pendingDeleteId.startsWith("member_"))pendingDeleteId=null;}
function executeDelete(){if(pendingDeleteId===null)return;if(typeof pendingDeleteId==="string"&&pendingDeleteId.startsWith("member_")){members=members.filter(x=>x.id!==parseInt(pendingDeleteId.replace("member_","")));closeDelPop();renderMemberGrid();renderLoginList();scheduleSave();return;}const task=tasks.find(t=>t.id===pendingDeleteId);addHistory("del",`"${task?.task||""}" 삭제`);tasks=tasks.filter(t=>t.id!==pendingDeleteId);delete checks[pendingDeleteId];delete assignees[pendingDeleteId];pendingDeleteId=null;closeDelPop();closePopover();renderAll();}
function toggleMaster(){const p=document.getElementById("master-panel");const s=p.style.display==="none";p.style.display=s?"block":"none";if(s)renderBadgeMaster();}
function renderBadgeMaster(){const el=document.getElementById("badge-master-list");el.innerHTML="";BADGES.forEach((b,i)=>{const d=document.createElement("div");d.className="badge-item";d.style.cssText=`background:${b.bg};color:${b.ft}`;d.innerHTML=`${esc(b.name)}<span class="badge-ic" onclick="editBadge(${i})">${SVG.edit}</span><span class="badge-ic" onclick="deleteBadge(${i})">${SVG.x}</span>`;el.appendChild(d);});}
function addBadge(){const name=document.getElementById("new-badge-name").value.trim();if(!name||BADGES.find(b=>b.name===name)){alert(!name?"상태명을 입력하세요.":"이미 존재합니다.");return;}BADGES.push({name,bg:document.getElementById("new-badge-bg").value,ft:document.getElementById("new-badge-ft").value});document.getElementById("new-badge-name").value="";renderBadgeMaster();scheduleSave();}
function editBadge(i){const n=prompt("상태명 수정",BADGES[i].name);if(n){BADGES[i].name=n.trim();renderBadgeMaster();scheduleSave();}}
function deleteBadge(i){if(!confirm(`'${BADGES[i].name}' 삭제?`))return;BADGES.splice(i,1);renderBadgeMaster();scheduleSave();}
function calcStats(){const total=tasks.length,done=tasks.filter(t=>checks[t.id]).length,pct=total?Math.round(done/total*100):0;document.getElementById("d-total-pct").textContent=pct+"%";document.getElementById("d-total-sub").textContent=`${done} / ${total} 완료`;document.getElementById("d-total-bar").style.width=pct+"%";document.getElementById("top-sub-count").textContent=`총 ${total}개 항목`;const mst=tasks.filter(t=>t.b==="마일스톤"),msd=mst.filter(t=>checks[t.id]).length,msp=mst.length?Math.round(msd/mst.length*100):0;document.getElementById("d-ms-pct").textContent=msp+"%";document.getElementById("d-ms-sub").textContent=`${msd} / ${mst.length} 완료`;document.getElementById("d-ms-bar").style.width=msp+"%";if(currentFilter!=="all"){const wt=tasks.filter(t=>t.w===currentFilter),wd=wt.filter(t=>checks[t.id]).length,wp=wt.length?Math.round(wd/wt.length*100):0;document.getElementById("d-week-pct").textContent=wp+"%";document.getElementById("d-week-sub").textContent=currentFilter+" 진행 중";document.getElementById("d-week-bar").style.width=wp+"%";}else{document.getElementById("d-week-pct").textContent="—";document.getElementById("d-week-sub").textContent="주차 선택 시 표시";document.getElementById("d-week-bar").style.width="0%";}}
function renderTrackBars(){const el=document.getElementById("track-bars");el.innerHTML="";Object.entries(TRACK_META).forEach(([k,m])=>{const tt=tasks.filter(t=>t.t===k);if(!tt.length)return;const done=tt.filter(t=>checks[t.id]).length,pct=Math.round(done/tt.length*100);el.innerHTML+=`<div class="track-row"><div class="track-name"><span style="width:8px;height:8px;border-radius:50%;background:${m.color};display:inline-block;flex-shrink:0"></span>${m.name}</div><div class="track-bw"><div class="track-bf" style="width:${pct}%;background:${m.color}"></div></div><div class="track-pct">${pct}%</div></div>`;});}
function renderWeekMini(){const el=document.getElementById("week-mini");el.innerHTML="";[...new Set(tasks.map(t=>t.w))].sort((a,b)=>WEEK_ORDER.indexOf(a)-WEEK_ORDER.indexOf(b)).forEach(w=>{const wt=tasks.filter(t=>t.w===w),done=wt.filter(t=>checks[t.id]).length,pct=wt.length?Math.round(done/wt.length*100):0,isActive=currentFilter===w;const d=document.createElement("div");d.className="wm-item";d.style.opacity=isActive?"1":".6";d.onclick=()=>filterWeek(w,null);d.innerHTML=`<div class="wm-bw"><div class="wm-bf" style="height:${pct}%;background:${isActive?"#0B3D91":"#1A5FB4"}"></div></div><div class="wm-lbl">${w}</div><div class="wm-pct">${pct}%</div>`;el.appendChild(d);});}
function renderWeekFilterBtns(){const el=document.getElementById("week-filter-btns");el.innerHTML="";[...new Set(tasks.map(t=>t.w))].sort((a,b)=>WEEK_ORDER.indexOf(a)-WEEK_ORDER.indexOf(b)).forEach(w=>{const btn=document.createElement("button");btn.className="wf-btn"+(currentFilter===w?" active":"");btn.textContent=w;btn.onclick=()=>filterWeek(w,btn);el.appendChild(btn);});}
function filterWeek(w,btn){currentFilter=w;document.querySelectorAll(".wf-btn").forEach(b=>b.classList.remove("active"));if(btn)btn.classList.add("active");else document.querySelectorAll(".wf-btn").forEach(b=>{if(b.textContent===w)b.classList.add("active");});if(w==="all")document.querySelector(".wf-btn")?.classList.add("active");renderTable();calcStats();renderWeekMini();}
function renderTable(){const tbody=document.getElementById("tbody");tbody.innerHTML="";const weeks=[...new Set(tasks.map(t=>t.w))].sort((a,b)=>WEEK_ORDER.indexOf(a)-WEEK_ORDER.indexOf(b));const filtered=currentFilter==="all"?weeks:[currentFilter];let prevWeek=null;filtered.forEach(w=>{if(currentFilter==="all"&&SEP_MAP[w]){const tr=document.createElement("tr");tr.className="sep-row";tr.innerHTML=`<td colspan="8">${SEP_MAP[w]}</td>`;tbody.appendChild(tr);}tasks.filter(t=>t.w===w).forEach(task=>{const isNew=task.w!==prevWeek,tm=TRACK_META[task.t]||{name:task.t,cls:"t-core",color:"#888"},isDone=checks[task.id];const av=assignees[task.id]||[];const MAX_AV=2;const avHtml=(()=>{const vis=av.slice(0,MAX_AV);const rest=av.length-MAX_AV;const allNames=av.map(mid=>{const m=members.find(x=>x.id===mid);return m?m.name:"";}).filter(Boolean).join(", ");const html=vis.map(mid=>{const m=members.find(x=>x.id===mid);if(!m)return"";const c=avColors(m.colorIdx);return`<span class="av-sm" style="background:${c.bg};color:${c.ft}" title="${esc(allNames)}">${esc(initials(m.name))}</span>`;}).join("");return html+(rest>0?`<span class="av-more" title="${esc(allNames)}">+${rest}</span>`:"");})();const bdgHtml=isNew&&task.b?(()=>{const bg=BADGES.find(x=>x.name===task.b);return bg?`<span style="display:inline-block;font-size:11px;font-weight:600;padding:3px 8px;border-radius:999px;background:${bg.bg};color:${bg.ft};margin-left:6px;vertical-align:middle">${esc(task.b)}</span>`:""})():"";const tr=document.createElement("tr");tr.id="row-"+task.id;if(isDone)tr.classList.add("done-row");tr.innerHTML=`<td class="tc"><input type="checkbox" ${isDone?"checked":""} onchange="toggle(${task.id})"></td><td class="td-week tc">${isNew?task.w:""}</td><td class="td-date">${isNew&&task.d?task.d:""}</td><td class="td-main">${isNew&&task.m?esc(task.m):""}${isNew?bdgHtml:""}</td><td><span class="tp ${tm.cls}"><span style="width:7px;height:7px;border-radius:50%;background:${tm.color};display:inline-block;flex-shrink:0"></span>${tm.name}</span></td><td><span class="task-text">${esc(task.task)}</span></td><td><div class="assignees">${avHtml||`<span style="font-size:12px;color:var(--text3)">—</span>`}</div></td><td class="tc"><div class="act-btns"><button class="btn btn-sm btn-ghost" onclick="openEditPopover(${task.id},this)">${SVG.edit}</button></div></td>`;tbody.appendChild(tr);prevWeek=task.w;});});}
function renderAll(){renderWeekFilterBtns();renderTable();calcStats();renderTrackBars();renderWeekMini();}
